# 1. laboratorijska vježba iz Numeričke matematike

Ime i prezime: *Filip Ćelepirović*

1. a) Napišite primjer jedne računske operacije koju ste izvršili u računalu, a da pri tome ne dobijete vrijednost koja se dobije egzaktno, računajući na papiru

In [2]:
# Ovdje ide rješenje

rezultat = 0.1 + 0.2
print(rezultat)  


0.30000000000000004


1. b) Navedite jedan primjer u kojem zbrajamo bojeve različitog reda veličine, te se rezultat u računalu razlikuje od egzaktnog.

In [6]:
# Ovdje ide rješenje

veliki_broj = 1e16
mali_broj = 1.0
rezultat = veliki_broj + mali_broj
print(rezultat)

1e+16


   2 . Napišite primjer računske operacije koja u računalu daje izlaz *inf* i operacije koja kao izlaz daje *nan*

In [12]:
# Ovdje ide rješenje

rezultat = 1e308 * 1e10
print(rezultat)

rezultat = float('nan') + 5
print(rezultat)  

inf
nan


3 a). U računalu rješavamo kvadratnu jednadžbu.
  $$(x+10^{9})(x-10^{-9})=0$$
  odnosno jednadžbu 
  $$x^2+(10^{9}-10^{-9})x-1=0$$
  Odredite rješenja koristeći formulu 
  $$x_{1/2}=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$$
 

In [14]:
# Ovdje ide rješenje

import math

# koeficijenti jednadzbe
a = 1
b = 10**9 - 10**-9
c = -1

# diskriminanta
D = b**2 - 4 * a * c

# rjesenja
x1 = (-b + math.sqrt(D)) / (2 * a)
x2 = (-b - math.sqrt(D)) / (2 * a)

print(x1)
print(x2)


0.0
-1000000000.0


3 b) Razlikuju li se rješenja od onih koje računamo na papiru? Iskoristite Vietovu formulu za nalaženje problemtičnog rješenja (osim da koristimo naredbu roots)?

In [17]:
# Ovdje ide rješenje

import numpy as np

# koeficijenti 
a = 1
b = 10**9 - 10**-9
c = -1

# kvadratnom formulom
discriminant = b**2 - 4 * a * c
x1 = (-b + np.sqrt(discriminant)) / (2 * a)
x2 = (-b - np.sqrt(discriminant)) / (2 * a)

# Vieteove formule 
sum_roots = -b / a
product_roots = c / a


print("Rješenja iz kvadratne formule:")
print("x1 =", x1)
print("x2 =", x2)
print('\n')

print("Zbroj korijena (Viete):", sum_roots)
print("Produkt korijena (Viete):", product_roots)
print('\n')

print("Zbroj rješenja (izračunato):", x1 + x2)
print("Produkt rješenja (izračunato):", x1 * x2)


Rješenja iz kvadratne formule:
x1 = 0.0
x2 = -1000000000.0


Zbroj korijena (Viete): -1000000000.0
Produkt korijena (Viete): -1.0


Zbroj rješenja (izračunato): -1000000000.0
Produkt rješenja (izračunato): -0.0


4 . Prepostavimo da imamo singularan sustav
 $$x+7y=3$$
 $$0.1x+0.7y=0.3$$
 
Riješite sustav koristeći [link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html).
 Zašto smo dobili samo jedno rješenje, a u realnosti ih ima beskonačno mnogo? Što kada biste koeficijente druge jednadžbe zapisali kao $(1\cdot0.1)$ i $(7\cdot0.1)$ te drugu komponentu vektora b kao $3\cdot0.1$, biste li dobili isto samo jedno rješenje? 

In [18]:
# ovdje ide rješenje

import numpy as np

# Matrica koeficijenata
A = np.array([[1, 7], [0.1, 0.7]])
# Vektor desne strane
b = np.array([3, 0.3])

# Rješenje sustava
rjesenje = np.linalg.solve(A, b)
rjesenje


array([-0.5,  0.5])

5 a. Odredite $PLU$ dekompoziciju matrice 
$$A=\begin{bmatrix} 2 & 1 & 3 & 4\\ -2 & 1 &-1& -2\\ 4 & 4& 5& 11\\ -2 & 1 & -7 & -1
\end{bmatrix}$$
koristeći biblioteku SciPy, te ispišite matrice $P$ (odnosno $P_1=P^T$), $L$, $U$. tako da je $P_1A=LU.$

In [23]:
#Ovdje ide rješenje

from scipy.linalg import lu

# Matrica A
A = np.array([[2, 1, 3, 4], [-2, 1, 2, 5], [4, 5, -1, 1], [-2, -1, -2, -1]])

# PLU dekompozicija
P, L, U = lu(A)

print(P)
print('\n')

print(L)
print('\n')

print(U)
print('\n')

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


[[ 1.          0.          0.          0.        ]
 [-0.5         1.          0.          0.        ]
 [ 0.5        -0.42857143  1.          0.        ]
 [-0.5         0.42857143 -0.75862069  1.        ]]


[[ 4.          5.         -1.          1.        ]
 [ 0.          3.5         1.5         5.5       ]
 [ 0.          0.          4.14285714  5.85714286]
 [ 0.          0.          0.          1.5862069 ]]




5 b.Koristeći već ugrađenu funkciju iz biblioteke scipy za rješavanje trokutastih sustava riješite sustav $Ax=b$ ako je 
$$b=\begin{bmatrix}10\\ -4\\ 24\\-9\end{bmatrix}$$
odnosno riješite
$$Ly=P_1b$$
$$Ux=y$$
Pomoć je 
[ovaj link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_triangular.html#scipy.linalg.solve_triangular).

In [21]:
# Ovdje ide rješenje

from scipy.linalg import solve_triangular

# Vektor b
b = np.array([10, -4, -24, -9])

# Računanje Pb
Pb = np.dot(P, b)

# Sustav Ly = Pb
y = solve_triangular(L, Pb, lower=True)

# Sustav Ux = y
x = solve_triangular(U, y)

print(x)


[ 1.57608696 -4.52173913  6.02173913 -1.67391304]


6 . Riješite sustav  $Ax=b$, gdje je $A$ trodijagonalna matrica 
$$A=\begin{bmatrix} 2 & 1 & 0 & 0 & 0\\ -1 & 2 & 2& 0 & 0\\ 0& -1& 2& 3& 0\\ 0 & 0 & -1 & 2 & 4\\
0& 0& 0 &-1& 2
\end{bmatrix}\quad b=\begin{bmatrix} 3\\ 3\\4\\5\\ 1 \end{bmatrix}$$
koristeći funkciju definiranu [ovaj link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_banded.html#scipy.linalg.solve_banded)

In [45]:
#Ovdje ide rješenje


import numpy as np
from scipy.linalg import solve_banded


upper_band = [1, 2, 3, 4]  
main_band = [2, 2, 2, 2, 2] 
lower_band = [-1, -1, -1, -1]  


ab = np.array([
    [0] + upper_band,
    main_band,  
    lower_band + [0]  
])


b = np.array([3, 3, 4, 5, 1])


x = solve_banded((1, 1), ab, b)

print(x)


[1. 1. 1. 1. 1.]


7.a) Zadana je matrica 
$$A=\begin{bmatrix} 1& 2 & 4\\ 2& 10 & 14\\ 4 & 14 & 29\end{bmatrix}$$
Odredite faktorizaciju Choleskog koristeći funkciju [link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.cholesky.html)

In [32]:
# ovdje ide rješenje


A = np.array([
    [1, 2, 4],
    [2, 10, 14],
    [4, 14, 29]
])


try:
    L = np.linalg.cholesky(A)
except np.linalg.LinAlgError:
    L = "Cholesky faktorizacija ne postoji jer matrica nije pozitivno definitna."

print(L)

[[1.         0.         0.        ]
 [2.         2.44948974 0.        ]
 [4.         2.44948974 2.64575131]]


7b)Zadana je matrica 
$$A=\begin{bmatrix} 1& 2 & 4\\ 2& 1 & 14\\ 4 & 14 & 29\end{bmatrix}$$
Odredite faktorizaciju Choleskog, ako postoji.

In [31]:
# Ovdje ide rješenje


A = np.array([
    [1, 2, 4],
    [2, 1, 14],
    [4, 14, 29]
])


try:
    L = np.linalg.cholesky(A)
except np.linalg.LinAlgError:
    L = "Cholesky faktorizacija ne postoji jer matrica nije pozitivno definitna."

print(L)

Cholesky faktorizacija ne postoji jer matrica nije pozitivno definitna.


8 . Ispiši svojstvene vrijednosti za matricu iz zadatka 7a i 7b. Koja je poveznica  s pozitivnom definitnošću?

In [35]:
# ovdje ide rješenje

A1 = np.array([
    [1, 2, 4],
    [2, 10, 14],
    [4, 14, 29]
])


A2 = np.array([
    [1, 2, 4],
    [2, 1, 14],
    [4, 14, 29]
])


eigenvalues1 = np.linalg.eigvals(A1)
eigenvalues2 = np.linalg.eigvals(A2)

print(eigenvalues1)
print(eigenvalues2) # Ima jednu negativnu svojstvenu vrijednost pa nema faktorizaciju Choleskog

[36.97456674  0.4392197   2.58621356]
[35.37787793  0.44001951 -4.81789744]


9 . Zadan je vektor 
$$x=\begin{bmatrix} 3\\ 5\\ 2\\ 7\\ 5\end{bmatrix}$$
Koristeći funkcije [ovaj link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) izračunajte normu ovog vektora i to 1-normu, $\infty$-normu i euklidsku normu.

In [37]:
# ovdje ide rješenje

from numpy.linalg import norm


x = np.array([3, 5, 2, 7, 5])

norm_1 = norm(x, ord=1)
norm_inf = norm(x, ord=np.inf)
norm_euclidean = norm(x, ord=2)

print(norm_1)
print(norm_inf)
print(norm_euclidean)


22.0
7.0
10.583005244258363


10 .  Zadana je matrica 
$$F=\begin{bmatrix}
300& -590 & 850& -561\\
1& -1 & 0& 0\\
0& 1& -1& 0\\
0& 0& 1& -1\\
\end{bmatrix}$$
Odredite $\infty$- normu ove matrice koristeći [ovaj link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) te uvjetovanost ove matrice u $\infty$- normi

In [42]:
F = np.array([
    [300, -590, 850, -561],
    [1, -1, 0, 0],
    [0, 1, -1, 0],
    [0, 0, 1, -1]
])


inf_norm = norm(F, ord=np.inf)

condition = np.linalg.cond(F, p=np.inf)


print(inf_norm)
print(condition)

2301.0
2650752.0000000102


11 . Zadana je matrica 
$$\begin{bmatrix} -9000 & 8000 & 8000\\ 7000 & 1& 0\\ 7000 & 0  & 0\end{bmatrix}$$
Probajte pronaći dijagonalnu matricu $D$ tako da matrica $DAD$ ima manju (odnosno bolju) uvjetovanost, te ispišite tu uvjetovanost.

In [41]:
import numpy as np
from numpy.linalg import cond


A = np.array([
    [-9000, 8000, 8000],
    [7000, 1, 0],
    [7000, 0, 0]
])

# uvjetovanost matrice A
initial_condition = cond(A)
print(initial_condition)

# matrica D s manjom uvjetovanošću
D = np.diag([1/9000, 1/7000, 1/7000])

# transformirana matrica DAD
DAD = D @ A @ D

# uvjetovanost matrice DAD
improved_condition = cond(DAD)
print(improved_condition)




32154.864190318127
22929.27177067454
